import { z } from 'zod';

/**
 * Client memory — the layer that lets the assistant know a person rather than a
 * portfolio.
 *
 * The product goal is that a client feels "Rosillo knows me". The engineering
 * problem underneath it is that a system which *claims* to remember your family can
 * do real harm in three distinct ways, and each gets a structural answer here rather
 * than a instruction in a prompt:
 *
 * 1. **It can invent.** "I remember you bought a car" when nobody said so is worse
 *    than saying nothing — it is a lie told warmly, and it destroys exactly the trust
 *    the feature exists to build. So a memory cannot be created by the model. Every
 *    record carries `provenance` naming a human act: the client said it, in a
 *    conversation with an id, on a date; or an adviser recorded it. `MODEL_INFERRED`
 *    is deliberately not a member of that union. There is no way to spell it.
 *
 * 2. **It can over-reach.** Knowing a daughter's age is useful for a travel policy
 *    and unwelcome in a cold sales call. Consent is therefore scoped by purpose and
 *    checked before the model runs, in the same way `AuthorisedScope` is — not
 *    filtered out of a draft afterwards.
 *
 * 3. **It can hold other people's data.** A child's name and age is personal data
 *    about a person who is not the account holder and who has not consented to
 *    anything. Those records are marked `aboutThirdParty` and are subject to
 *    narrower rules: never used to justify contacting the third party, never
 *    retained past the purpose, and deletable by the account holder on request.
 *
 * The client can see, correct and delete all of it. That is not a compliance
 * afterthought — a memory you cannot inspect is a memory you cannot trust.
 *
 * SYNTHETIC DATA ONLY.
 */

/** What kind of thing is remembered. Closed set: a new kind is a product decision. */
export const MEMORY_KINDS = [
  'FAMILY_MEMBER',
  'IMPORTANT_DATE',
  'LIFE_EVENT',
  'PREFERENCE',
  'CIRCUMSTANCE',
  'CONTACT_NOTE',
] as const;
export const memoryKindSchema = z.enum(MEMORY_KINDS);
export type MemoryKind = z.infer<typeof memoryKindSchema>;

/**
 * How the platform knows this.
 *
 * Note what is absent: there is no `MODEL_INFERRED`. A memory is something a person
 * told Rosillo, or something an adviser wrote down. If the model believes it has
 * spotted a pattern, that is a hypothesis for an adviser, not a memory to recite
 * back to the client as though it were remembered.
 */
export const MEMORY_SOURCES = ['CLIENT_STATED', 'ADVISER_RECORDED', 'CLIENT_PROFILE_FORM'] as const;
export const memorySourceSchema = z.enum(MEMORY_SOURCES);
export type MemorySource = z.infer<typeof memorySourceSchema>;

export const memoryProvenanceSchema = z.object({
  source: memorySourceSchema,
  /** The conversation or form the statement came from, so it can be shown and audited. */
  originId: z.string().min(1).max(120),
  /** When the person said it — not when the row was written. */
  statedAt: z.string().datetime(),
  /** The adviser who recorded it, when a human did. */
  recordedByEmployeeId: z.string().max(120).optional(),
});
export type MemoryProvenance = z.infer<typeof memoryProvenanceSchema>;

/**
 * Purposes a memory may be used for. Consent is granted per purpose, because
 * "you may use my daughter's age to check her travel cover" is a different
 * permission from "you may use it to sell me things".
 */
export const MEMORY_PURPOSES = [
  /** Answering something the client asked, right now, in this conversation. */
  'ANSWER_IN_CONVERSATION',
  /** Deciding whether a cover still fits, without contacting anyone. */
  'COVERAGE_REVIEW',
  /** Reaching out unprompted. The one that needs the most explicit permission. */
  'PROACTIVE_CONTACT',
  /** Giving an adviser context on a handoff they are already handling. */
  'ADVISER_CONTEXT',
] as const;
export const memoryPurposeSchema = z.enum(MEMORY_PURPOSES);
export type MemoryPurpose = z.infer<typeof memoryPurposeSchema>;

export const clientMemorySchema = z.object({
  id: z.string().min(1).max(120),
  /** The account this memory belongs to. */
  accountId: z.string().min(1).max(120),
  kind: memoryKindSchema,
  /** Short human label — "Daughter", "House renovation", "Prefers WhatsApp". */
  label: z.string().min(1).max(120),
  /** The value as the person expressed it. Never a paraphrase generated by a model. */
  value: z.string().min(1).max(400),
  /** A date the memory is anchored to, where it has one: a birthday, a trip, a move. */
  onDate: z.string().max(10).optional(),
  provenance: memoryProvenanceSchema,
  /** Purposes the client has allowed for this record specifically. */
  allowedPurposes: z.array(memoryPurposeSchema).max(MEMORY_PURPOSES.length),
  /**
   * True when the memory is about someone other than the account holder — a child, a
   * partner. Narrower handling: see the header, and `usableFor` below.
   */
  aboutThirdParty: z.boolean().default(false),
  /**
   * Special-category data under GDPR Article 9 — health, beliefs, and so on. The
   * platform stores these only when a client volunteers them, and never uses them to
   * initiate contact.
   */
  specialCategory: z.boolean().default(false),
  /** When the client last confirmed this is still true. Memories go stale. */
  confirmedAt: z.string().datetime().optional(),
  /** Set when the client deletes it; the row is tombstoned, never silently dropped. */
  forgottenAt: z.string().datetime().optional(),
});
export type ClientMemory = z.infer<typeof clientMemorySchema>;

/**
 * May this memory be used for this purpose, right now?
 *
 * Deterministic and total — every branch is a rule someone can read, argue with and
 * change. Nothing here consults a model.
 */
export function usableFor(memory: ClientMemory, purpose: MemoryPurpose): boolean {
  // A forgotten memory is unusable for everything. Deletion means deletion.
  if (memory.forgottenAt) return false;
  if (!memory.allowedPurposes.includes(purpose)) return false;

  // Special-category data never justifies an unprompted approach. A client may tell
  // us about a condition so we can answer them; that is not permission to bring it up.
  if (memory.specialCategory && purpose === 'PROACTIVE_CONTACT') return false;

  return true;
}

/** The memories usable for a purpose, in one call, so no caller can forget the check. */
export function memoriesFor(memories: ClientMemory[], purpose: MemoryPurpose): ClientMemory[] {
  return memories.filter((memory) => usableFor(memory, purpose));
}

/**
 * How the assistant is allowed to refer to a memory in front of the client.
 *
 * "Make it clear when information comes from previous conversations" is a product
 * rule with a precise consequence: the sentence has to be attributable. This returns
 * the attribution, and the surface renders it beside the memory rather than letting
 * the model phrase it — a model asked to say where something came from will
 * eventually say something plausible instead of something true.
 */
export function attribution(memory: ClientMemory, locale: 'es' | 'en'): string {
  const date = memory.provenance.statedAt.slice(0, 10);
  if (locale === 'es') {
    switch (memory.provenance.source) {
      case 'CLIENT_STATED':
        return `Nos lo contaste el ${date}`;
      case 'ADVISER_RECORDED':
        return `Lo anotó un asesor de Rosillo el ${date}`;
      case 'CLIENT_PROFILE_FORM':
        return `Lo indicaste en tu perfil el ${date}`;
    }
  }
  switch (memory.provenance.source) {
    case 'CLIENT_STATED':
      return `You told us on ${date}`;
    case 'ADVISER_RECORDED':
      return `A Rosillo adviser noted this on ${date}`;
    case 'CLIENT_PROFILE_FORM':
      return `You entered this in your profile on ${date}`;
  }
}

/**
 * Memories a client has not confirmed for a long time.
 *
 * A relationship product decays badly: "how is the house renovation going?" two years
 * after it finished is worse than never having asked. Rather than guessing, the
 * platform asks the client to confirm, and stops using stale records to initiate
 * contact until they do.
 */
export const STALE_AFTER_DAYS = 540;

export function isStale(memory: ClientMemory, today: string): boolean {
  const anchor = memory.confirmedAt ?? memory.provenance.statedAt;
  const days = (Date.parse(`${today}T00:00:00Z`) - Date.parse(anchor)) / 86_400_000;
  return days > STALE_AFTER_DAYS;
}
