import type { Customer360Dataset } from '../model';
import {
  account,
  claim,
  coverageTerm,
  document,
  insuredObject,
  organisation,
  passages,
  person,
  policy,
  receipt,
  relationship,
} from './builders';

/**
 * Hand-crafted anchor scenarios.
 *
 * These are the cases the evaluation suite and the authorisation tests assert
 * against, so their ids are stable and their shape is deliberate. Each anchor exists
 * to make a specific failure mode reproducible:
 *
 *   A  multi-policy household with *partial* delegation — access is per-grant
 *   B  an unrelated client with the same surname — the classic mis-resolution
 *   C  an SME where an employee sees less than the administrator
 *   D  ERP and policy schedule disagree on the premium — a conflict, not an average
 *   E  a schedule superseded by an endorsement — stale evidence must not win
 *   F  an open claim with chronology, and a special-category health claim
 *   G  a fleet/logistics operator with commercial lines
 *   H  an English-speaking student
 *
 * SYNTHETIC DATA ONLY. Every name, identifier and document below is invented.
 */

export function buildAnchors(): Customer360Dataset {
  // ── Anchor A — Familia García Molina ───────────────────────────────────────
  // Ana holds delegated access over her spouse Luis, but only for policies.
  // Her adult daughter Marta shares the household and grants her nothing.
  const parties = [
    person({
      id: 'party_ana',
      name: 'Ana García Molina',
      surname: 'García Molina',
      email: 'ana@cliente.test',
      phone: '+34 600 000 101',
      taxIdSynthetic: 'X0000101A',
      city: 'Madrid',
    }),
    person({
      id: 'party_luis',
      name: 'Luis García Molina',
      surname: 'García Molina',
      email: 'luis@cliente.test',
      phone: '+34 600 000 102',
      taxIdSynthetic: 'X0000102B',
      city: 'Madrid',
    }),
    person({
      id: 'party_marta',
      name: 'Marta García Ruiz',
      surname: 'García Ruiz',
      email: 'marta@cliente.test',
      phone: '+34 600 000 103',
      taxIdSynthetic: 'X0000103C',
      city: 'Londres',
    }),

    // ── Anchor B — same surname, entirely unrelated ──────────────────────────
    person({
      id: 'party_carlos',
      name: 'Carlos García Pérez',
      surname: 'García Pérez',
      email: 'carlos@cliente.test',
      phone: '+34 600 000 201',
      taxIdSynthetic: 'X0000201D',
      city: 'Valencia',
    }),

    // ── Anchor C — Talleres Serrano S.L. ─────────────────────────────────────
    person({
      id: 'party_elena',
      name: 'Elena Serrano Vidal',
      surname: 'Serrano Vidal',
      email: 'elena@cliente.test',
      phone: '+34 600 000 301',
      taxIdSynthetic: 'X0000301E',
      city: 'Zaragoza',
    }),
    person({
      id: 'party_javier',
      name: 'Javier Ortiz Lozano',
      surname: 'Ortiz Lozano',
      email: 'javier@cliente.test',
      phone: '+34 600 000 302',
      taxIdSynthetic: 'X0000302F',
      city: 'Zaragoza',
    }),
    organisation({
      id: 'org_serrano',
      name: 'Talleres Serrano S.L.',
      activity: 'Reparación de vehículos',
      employeeCount: 14,
      email: 'admin@talleresserrano.test',
      phone: '+34 976 000 300',
      taxIdSynthetic: 'B00000300',
      city: 'Zaragoza',
    }),

    // ── Anchor D — conflicting premium ───────────────────────────────────────
    person({
      id: 'party_rosa',
      name: 'Rosa Delgado Nieto',
      surname: 'Delgado Nieto',
      email: 'rosa@cliente.test',
      phone: '+34 600 000 401',
      taxIdSynthetic: 'X0000401G',
      city: 'Sevilla',
    }),

    // ── Anchor E — superseded schedule ───────────────────────────────────────
    person({
      id: 'party_miguel',
      name: 'Miguel Torres Aguado',
      surname: 'Torres Aguado',
      email: 'miguel@cliente.test',
      phone: '+34 600 000 501',
      taxIdSynthetic: 'X0000501H',
      city: 'Bilbao',
    }),

    // ── Anchor F — special-category health claim ─────────────────────────────
    person({
      id: 'party_pilar',
      name: 'Pilar Ramos Cano',
      surname: 'Ramos Cano',
      email: 'pilar@cliente.test',
      phone: '+34 600 000 601',
      taxIdSynthetic: 'X0000601I',
      city: 'Madrid',
    }),

    // ── Anchor G — fleet / logistics ─────────────────────────────────────────
    person({
      id: 'party_tomas',
      name: 'Tomás Iglesias Ferrer',
      surname: 'Iglesias Ferrer',
      email: 'tomas@cliente.test',
      phone: '+34 600 000 701',
      taxIdSynthetic: 'X0000701J',
      city: 'Barcelona',
    }),
    organisation({
      id: 'org_translog',
      name: 'Translog Ibérica S.L.',
      activity: 'Transporte de mercancías por carretera',
      employeeCount: 42,
      email: 'flota@translog.test',
      phone: '+34 934 000 700',
      taxIdSynthetic: 'B00000700',
      city: 'Barcelona',
    }),

    // ── Anchor H — English-speaking student ──────────────────────────────────
    person({
      id: 'party_sophie',
      name: 'Sophie Bennett',
      surname: 'Bennett',
      email: 'sophie@cliente.test',
      phone: '+34 600 000 801',
      taxIdSynthetic: 'Y0000801K',
      city: 'Salamanca',
    }),
  ];

  const accounts = [
    account({ id: 'acc_ana', partyId: 'party_ana', email: 'ana@cliente.test', displayName: 'Ana García' }),
    account({ id: 'acc_luis', partyId: 'party_luis', email: 'luis@cliente.test', displayName: 'Luis García' }),
    account({ id: 'acc_marta', partyId: 'party_marta', email: 'marta@cliente.test', displayName: 'Marta García' }),
    account({
      id: 'acc_carlos',
      partyId: 'party_carlos',
      email: 'carlos@cliente.test',
      displayName: 'Carlos García',
    }),
    account({
      id: 'acc_elena',
      partyId: 'party_elena',
      email: 'elena@cliente.test',
      displayName: 'Elena Serrano',
      organisationIds: ['org_serrano'],
    }),
    account({
      id: 'acc_javier',
      partyId: 'party_javier',
      email: 'javier@cliente.test',
      displayName: 'Javier Ortiz',
      organisationIds: ['org_serrano'],
    }),
    account({ id: 'acc_rosa', partyId: 'party_rosa', email: 'rosa@cliente.test', displayName: 'Rosa Delgado' }),
    account({
      id: 'acc_miguel',
      partyId: 'party_miguel',
      email: 'miguel@cliente.test',
      displayName: 'Miguel Torres',
    }),
    account({ id: 'acc_pilar', partyId: 'party_pilar', email: 'pilar@cliente.test', displayName: 'Pilar Ramos' }),
    account({
      id: 'acc_tomas',
      partyId: 'party_tomas',
      email: 'tomas@cliente.test',
      displayName: 'Tomás Iglesias',
      organisationIds: ['org_translog'],
    }),
    account({
      id: 'acc_sophie',
      partyId: 'party_sophie',
      email: 'sophie@cliente.test',
      displayName: 'Sophie Bennett',
      language: 'en',
    }),
  ];

  const relationships = [
    // Ana ⇄ Luis: married, but the delegation is deliberately partial. Ana may see
    // Luis's policies and nothing else — no claims, no documents, no receipts.
    relationship({
      id: 'rel_ana_luis',
      kind: 'DELEGATED_ACCESS',
      fromPartyId: 'party_ana',
      toPartyId: 'party_luis',
      grants: ['VIEW_POLICIES'],
      basis: 'Autorización firmada de consulta de pólizas entre cónyuges (2024-03-11)',
      effectiveFrom: '2024-03-11',
    }),
    // Luis holds no reciprocal authority over Ana. Marriage is not authority.
    relationship({
      id: 'rel_luis_ana_household',
      kind: 'SPOUSE',
      fromPartyId: 'party_luis',
      toPartyId: 'party_ana',
      grants: [],
      basis: 'Vínculo familiar registrado. No confiere acceso a datos.',
    }),
    // Marta is an adult household member. Ana sees nothing of hers.
    relationship({
      id: 'rel_ana_marta',
      kind: 'HOUSEHOLD_MEMBER',
      fromPartyId: 'party_ana',
      toPartyId: 'party_marta',
      grants: [],
      basis: 'Miembro del hogar mayor de edad. Sin autorización de acceso.',
    }),
    // Elena administers the company with full grants.
    relationship({
      id: 'rel_elena_serrano',
      kind: 'COMPANY_ADMIN',
      fromPartyId: 'party_elena',
      toPartyId: 'org_serrano',
      grants: ['VIEW_POLICIES', 'VIEW_CLAIMS', 'VIEW_DOCUMENTS', 'VIEW_RECEIPTS', 'CREATE_TASKS'],
      basis: 'Administradora única inscrita — poder de representación',
    }),
    // Javier works there. He may see policies only: not claims, receipts or documents.
    relationship({
      id: 'rel_javier_serrano',
      kind: 'COMPANY_EMPLOYEE',
      fromPartyId: 'party_javier',
      toPartyId: 'org_serrano',
      grants: ['VIEW_POLICIES'],
      basis: 'Empleado autorizado a consultar pólizas de flota (2025-09-01)',
      effectiveFrom: '2025-09-01',
    }),
    relationship({
      id: 'rel_tomas_translog',
      kind: 'FLEET_MANAGER',
      fromPartyId: 'party_tomas',
      toPartyId: 'org_translog',
      grants: ['VIEW_POLICIES', 'VIEW_CLAIMS', 'VIEW_DOCUMENTS', 'CREATE_TASKS'],
      basis: 'Responsable de flota — autorización operativa',
    }),
  ];

  // ── Documents ──────────────────────────────────────────────────────────────
  const documents = [
    document({
      id: 'doc_ana_auto_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Auto Allianz 2026',
      ownerPartyId: 'party_ana',
      policyId: 'pol_ana_auto',
      effectiveFrom: '2026-03-01',
      effectiveTo: '2027-03-01',
      passages: passages(
        [
          {
            heading: 'Datos del riesgo',
            text: 'Vehículo asegurado: Audi Q5 45 TFSI, matrícula 4821 KLM. Uso particular. Conductor habitual: Ana García Molina.',
          },
          {
            heading: 'Modalidad y franquicia',
            text: 'Modalidad contratada: Todo Riesgo con franquicia. La franquicia aplicable a los daños propios del vehículo asegurado es de 300 € por siniestro.',
          },
          {
            heading: 'Prima anual',
            text: 'Prima anual total: 742,30 €, con fraccionamiento semestral.',
          },
        ],
        'doc_ana_auto_cp',
      ),
    }),
    document({
      id: 'doc_ana_auto_cg',
      kind: 'POLICY_WORDING',
      title: 'Condiciones generales — Auto Allianz',
      ownerPartyId: 'party_ana',
      policyId: 'pol_ana_auto',
      effectiveFrom: '2026-03-01',
      passages: passages(
        [
          {
            heading: 'Robo del vehículo y de objetos',
            text: 'Queda cubierto el robo del vehículo asegurado y de sus accesorios fijos. No quedan cubiertos los objetos personales transportados en el interior del vehículo, salvo contratación expresa de la garantía de equipaje.',
          },
          {
            heading: 'Exclusiones generales',
            text: 'Quedan excluidos los daños producidos cuando el conductor carezca de permiso de conducción en vigor, así como los ocasionados en pruebas deportivas o de velocidad.',
          },
        ],
        'doc_ana_auto_cg',
      ),
    }),
    document({
      id: 'doc_ana_hogar_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Hogar Mapfre 2026',
      ownerPartyId: 'party_ana',
      policyId: 'pol_ana_hogar',
      effectiveFrom: '2026-01-15',
      effectiveTo: '2027-01-15',
      passages: passages(
        [
          {
            heading: 'Vivienda asegurada',
            text: 'Vivienda habitual sita en Calle Sintética 12, 3º B, Madrid. Superficie 95 m². Continente asegurado: 180.000 €. Contenido asegurado: 40.000 €.',
          },
          {
            heading: 'Objetos de especial valor',
            text: 'Los objetos de especial valor están cubiertos hasta un sublímite del 20% del capital de contenido, con un máximo de 3.000 € por objeto, salvo declaración expresa y tasación aportada.',
          },
          {
            heading: 'Daños por agua',
            text: 'Se cubren los daños por agua procedentes de la vivienda asegurada, incluida la localización y reparación de la avería. Franquicia: 150 € en daños por agua.',
          },
        ],
        'doc_ana_hogar_cp',
      ),
    }),
    document({
      id: 'doc_ana_certificado_hogar',
      kind: 'CERTIFICATE',
      title: 'Certificado de seguro de hogar',
      ownerPartyId: 'party_ana',
      policyId: 'pol_ana_hogar',
      effectiveFrom: '2026-01-15',
      effectiveTo: '2027-01-15',
      passages: passages(
        [
          {
            heading: 'Certificado',
            text: 'Se certifica que la vivienda sita en Calle Sintética 12, 3º B, Madrid, se encuentra asegurada mediante la póliza HOG-2026-0042 con vigencia hasta el 15 de enero de 2027.',
          },
        ],
        'doc_ana_certificado_hogar',
      ),
    }),

    // Anchor E — the superseded schedule and the endorsement that replaced it.
    document({
      id: 'doc_miguel_auto_cp_v1',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Auto AXA 2025 (sustituidas)',
      ownerPartyId: 'party_miguel',
      policyId: 'pol_miguel_auto',
      effectiveFrom: '2025-06-01',
      effectiveTo: '2026-05-20',
      supersededByDocumentId: 'doc_miguel_auto_supl',
      passages: passages(
        [
          {
            heading: 'Franquicia',
            text: 'La franquicia aplicable a los daños propios es de 300 € por siniestro.',
          },
        ],
        'doc_miguel_auto_cp_v1',
      ),
    }),
    document({
      id: 'doc_miguel_auto_supl',
      kind: 'ENDORSEMENT',
      title: 'Suplemento de modificación de franquicia — Auto AXA',
      ownerPartyId: 'party_miguel',
      policyId: 'pol_miguel_auto',
      effectiveFrom: '2026-05-21',
      effectiveTo: '2027-06-01',
      passages: passages(
        [
          {
            heading: 'Modificación de franquicia',
            text: 'Con efecto 21 de mayo de 2026, la franquicia aplicable a los daños propios del vehículo asegurado queda establecida en 150 € por siniestro, sustituyendo la anterior de 300 €.',
          },
        ],
        'doc_miguel_auto_supl',
      ),
    }),

    // Anchor D — the schedule that disagrees with the ERP on the premium.
    document({
      id: 'doc_rosa_hogar_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Hogar Generali 2026',
      ownerPartyId: 'party_rosa',
      policyId: 'pol_rosa_hogar',
      effectiveFrom: '2026-04-01',
      effectiveTo: '2027-04-01',
      passages: passages(
        [
          {
            heading: 'Prima anual',
            text: 'Prima anual total: 512,40 €, incluidos impuestos y recargos legalmente repercutibles.',
          },
          {
            heading: 'Capitales asegurados',
            text: 'Continente: 140.000 €. Contenido: 30.000 €. Franquicia general: 0 €.',
          },
        ],
        'doc_rosa_hogar_cp',
      ),
    }),

    document({
      id: 'doc_serrano_rc_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — RC General Zurich',
      ownerPartyId: 'org_serrano',
      policyId: 'pol_serrano_rc',
      effectiveFrom: '2026-02-01',
      effectiveTo: '2027-02-01',
      passages: passages(
        [
          {
            heading: 'Límite de indemnización',
            text: 'Límite máximo de indemnización por siniestro y año: 600.000 €. Sublímite por víctima: 300.000 €.',
          },
          {
            heading: 'Actividad asegurada',
            text: 'Actividad declarada: taller de reparación de vehículos, incluida la responsabilidad civil por trabajos ejecutados y vehículos en custodia hasta 60.000 €.',
          },
        ],
        'doc_serrano_rc_cp',
      ),
    }),
    document({
      id: 'doc_serrano_ciber_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Ciberriesgo Hiscox',
      ownerPartyId: 'org_serrano',
      policyId: 'pol_serrano_ciber',
      effectiveFrom: '2026-02-01',
      effectiveTo: '2027-02-01',
      passages: passages(
        [
          {
            heading: 'Garantías contratadas',
            text: 'Se cubren los gastos de respuesta a incidentes, la reconstrucción de datos y la pérdida de beneficios por interrupción de red, con un límite agregado de 250.000 € y una franquicia de 2.500 € por siniestro.',
          },
        ],
        'doc_serrano_ciber_cp',
      ),
    }),
    document({
      id: 'doc_sophie_viaje_cp',
      kind: 'POLICY_SCHEDULE',
      title: 'Condiciones particulares — Viaje y estudios Chubb',
      ownerPartyId: 'party_sophie',
      policyId: 'pol_sophie_viaje',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-06-30',
      passages: passages(
        [
          {
            heading: 'Asistencia médica',
            text: 'Gastos médicos por enfermedad o accidente en el extranjero hasta 30.000 €. Incluye repatriación sanitaria.',
          },
          {
            heading: 'Deportes de invierno',
            text: 'La práctica de deportes de invierno en pista señalizada queda cubierta. Quedan excluidos el esquí fuera de pista, el freeride y la participación en competiciones.',
          },
        ],
        'doc_sophie_viaje_cp',
      ),
    }),
    document({
      id: 'doc_ana_claim_agua',
      kind: 'CLAIM_EVIDENCE',
      title: 'Informe del perito — daños por agua',
      ownerPartyId: 'party_ana',
      claimId: 'clm_ana_agua',
      policyId: 'pol_ana_hogar',
      effectiveFrom: '2026-07-14',
      clientDownloadable: false,
      passages: passages(
        [
          {
            heading: 'Conclusión del perito',
            text: 'Se confirma la rotura de un latiguillo bajo el fregadero de la cocina. Daños en mobiliario de cocina y parqué del salón. Se solicita factura de reparación del latiguillo para cerrar la valoración.',
          },
        ],
        'doc_ana_claim_agua',
      ),
    }),
    document({
      id: 'doc_pilar_salud_parte',
      kind: 'CLAIM_EVIDENCE',
      title: 'Parte de asistencia — reembolso salud',
      ownerPartyId: 'party_pilar',
      claimId: 'clm_pilar_salud',
      policyId: 'pol_pilar_salud',
      effectiveFrom: '2026-06-20',
      classification: 'SPECIAL_CATEGORY',
      clientDownloadable: false,
      passages: passages(
        [
          {
            heading: 'Solicitud de reembolso',
            text: 'Solicitud de reembolso de asistencia especialista. Documentación clínica adjunta bajo tratamiento restringido.',
          },
        ],
        'doc_pilar_salud_parte',
      ),
    }),
  ];

  // ── Insured objects ────────────────────────────────────────────────────────
  const insuredObjects = [
    insuredObject({
      id: 'obj_ana_audi',
      kind: 'VEHICLE',
      label: 'Audi Q5 45 TFSI · 4821 KLM',
      attributes: { matricula: '4821 KLM', marca: 'Audi', modelo: 'Q5 45 TFSI', uso: 'Particular' },
    }),
    insuredObject({
      id: 'obj_ana_vivienda',
      kind: 'PROPERTY',
      label: 'Vivienda habitual · Calle Sintética 12, 3º B, Madrid',
      attributes: { direccion: 'Calle Sintética 12, 3º B, Madrid', superficie: '95 m²', tipo: 'Vivienda habitual' },
    }),
    insuredObject({
      id: 'obj_luis_seat',
      kind: 'VEHICLE',
      label: 'Seat León 1.5 TSI · 7734 MBN',
      attributes: { matricula: '7734 MBN', marca: 'Seat', modelo: 'León 1.5 TSI', uso: 'Particular' },
    }),
    insuredObject({
      id: 'obj_carlos_golf',
      kind: 'VEHICLE',
      label: 'Volkswagen Golf 1.4 TSI · 2210 JDR',
      attributes: { matricula: '2210 JDR', marca: 'Volkswagen', modelo: 'Golf 1.4 TSI', uso: 'Particular' },
    }),
    insuredObject({
      id: 'obj_miguel_bmw',
      kind: 'VEHICLE',
      label: 'BMW Serie 3 320d · 5567 LPT',
      attributes: { matricula: '5567 LPT', marca: 'BMW', modelo: 'Serie 3 320d', uso: 'Particular' },
    }),
    insuredObject({
      id: 'obj_serrano_taller',
      kind: 'BUSINESS_LOCATION',
      label: 'Taller · Polígono Sintético, nave 7, Zaragoza',
      attributes: { direccion: 'Polígono Sintético, nave 7, Zaragoza', superficie: '620 m²', actividad: 'Taller' },
    }),
    insuredObject({
      id: 'obj_serrano_furgon_1',
      kind: 'VEHICLE',
      label: 'Renault Master · 8891 KTR',
      attributes: { matricula: '8891 KTR', marca: 'Renault', modelo: 'Master', uso: 'Industrial' },
    }),
    insuredObject({
      id: 'obj_serrano_furgon_2',
      kind: 'VEHICLE',
      label: 'Citroën Jumpy · 3345 LMS',
      attributes: { matricula: '3345 LMS', marca: 'Citroën', modelo: 'Jumpy', uso: 'Industrial' },
    }),
    insuredObject({
      id: 'obj_translog_camion_1',
      kind: 'VEHICLE',
      label: 'MAN TGX 18.480 · 1102 NPQ',
      attributes: { matricula: '1102 NPQ', marca: 'MAN', modelo: 'TGX 18.480', uso: 'Transporte' },
    }),
    insuredObject({
      id: 'obj_translog_mercancias',
      kind: 'GOODS',
      label: 'Mercancías transportadas · ruta nacional',
      attributes: { ambito: 'Nacional', tipo: 'Mercancía general paletizada' },
    }),
    insuredObject({
      id: 'obj_rosa_vivienda',
      kind: 'PROPERTY',
      label: 'Vivienda habitual · Avenida Sintética 88, Sevilla',
      attributes: { direccion: 'Avenida Sintética 88, Sevilla', superficie: '78 m²', tipo: 'Vivienda habitual' },
    }),
  ];

  // ── Policies ───────────────────────────────────────────────────────────────
  const policies = [
    policy({
      id: 'pol_ana_auto',
      policyNumber: 'AUT-2026-0187',
      holderPartyId: 'party_ana',
      insurer: 'Allianz',
      product: 'AUTO',
      productLabel: 'Auto — Todo Riesgo con franquicia',
      inceptionDate: '2026-03-01',
      renewalDate: '2027-03-01',
      premium: 742.3,
      previousPremium: 661.5,
      insuredObjectIds: ['obj_ana_audi'],
      documentIds: ['doc_ana_auto_cp', 'doc_ana_auto_cg'],
    }),
    policy({
      id: 'pol_ana_hogar',
      policyNumber: 'HOG-2026-0042',
      holderPartyId: 'party_ana',
      insurer: 'Mapfre',
      product: 'HOGAR',
      productLabel: 'Hogar — Multirriesgo',
      inceptionDate: '2026-01-15',
      renewalDate: '2027-01-15',
      premium: 389.0,
      previousPremium: 372.15,
      insuredObjectIds: ['obj_ana_vivienda'],
      documentIds: ['doc_ana_hogar_cp', 'doc_ana_certificado_hogar'],
    }),
    policy({
      id: 'pol_ana_salud',
      policyNumber: 'SAL-2026-0311',
      holderPartyId: 'party_ana',
      insurer: 'DKV',
      product: 'SALUD',
      productLabel: 'Salud — Cuadro médico',
      inceptionDate: '2026-01-01',
      renewalDate: '2027-01-01',
      premium: 1180.0,
      previousPremium: 1094.4,
      documentIds: [],
    }),
    policy({
      id: 'pol_luis_auto',
      policyNumber: 'AUT-2026-0512',
      holderPartyId: 'party_luis',
      insurer: 'Línea Directa',
      product: 'AUTO',
      productLabel: 'Auto — Terceros ampliado',
      inceptionDate: '2026-06-01',
      renewalDate: '2027-06-01',
      premium: 421.75,
      insuredObjectIds: ['obj_luis_seat'],
    }),
    policy({
      id: 'pol_luis_vida',
      policyNumber: 'VID-2025-0090',
      holderPartyId: 'party_luis',
      insurer: 'Santalucía',
      product: 'VIDA',
      productLabel: 'Vida — Riesgo',
      inceptionDate: '2025-11-01',
      renewalDate: '2026-11-01',
      premium: 310.0,
    }),
    policy({
      id: 'pol_marta_viaje',
      policyNumber: 'VIA-2026-0777',
      holderPartyId: 'party_marta',
      insurer: 'Chubb',
      product: 'VIAJE',
      productLabel: 'Viaje y estancia — Estudiantes',
      inceptionDate: '2026-09-01',
      renewalDate: '2027-06-30',
      premium: 210.0,
    }),
    policy({
      id: 'pol_carlos_auto',
      policyNumber: 'AUT-2026-0901',
      holderPartyId: 'party_carlos',
      insurer: 'Mutua Sintética',
      product: 'AUTO',
      productLabel: 'Auto — Todo Riesgo',
      inceptionDate: '2026-02-10',
      renewalDate: '2027-02-10',
      premium: 655.2,
      insuredObjectIds: ['obj_carlos_golf'],
    }),
    policy({
      id: 'pol_carlos_hogar',
      policyNumber: 'HOG-2026-0455',
      holderPartyId: 'party_carlos',
      insurer: 'Mapfre',
      product: 'HOGAR',
      productLabel: 'Hogar — Multirriesgo',
      inceptionDate: '2026-05-01',
      renewalDate: '2027-05-01',
      premium: 298.4,
    }),
    policy({
      id: 'pol_serrano_rc',
      policyNumber: 'RCG-2026-0033',
      holderPartyId: 'org_serrano',
      insurer: 'Zurich',
      product: 'RC_GENERAL',
      productLabel: 'Responsabilidad Civil General',
      inceptionDate: '2026-02-01',
      renewalDate: '2027-02-01',
      premium: 2480.0,
      previousPremium: 2310.0,
      insuredObjectIds: ['obj_serrano_taller'],
      documentIds: ['doc_serrano_rc_cp'],
    }),
    policy({
      id: 'pol_serrano_comercio',
      policyNumber: 'COM-2026-0061',
      holderPartyId: 'org_serrano',
      insurer: 'Generali',
      product: 'COMERCIO',
      productLabel: 'Multirriesgo Comercio',
      inceptionDate: '2026-02-01',
      renewalDate: '2027-02-01',
      premium: 1740.5,
      insuredObjectIds: ['obj_serrano_taller'],
    }),
    policy({
      id: 'pol_serrano_flota',
      policyNumber: 'FLO-2026-0012',
      holderPartyId: 'org_serrano',
      insurer: 'Allianz',
      product: 'FLOTA',
      productLabel: 'Flota — 2 vehículos industriales',
      inceptionDate: '2026-02-01',
      renewalDate: '2027-02-01',
      premium: 3120.0,
      insuredObjectIds: ['obj_serrano_furgon_1', 'obj_serrano_furgon_2'],
    }),
    policy({
      id: 'pol_serrano_ciber',
      policyNumber: 'CIB-2026-0007',
      holderPartyId: 'org_serrano',
      insurer: 'Hiscox',
      product: 'CIBER',
      productLabel: 'Ciberriesgo PYME',
      inceptionDate: '2026-02-01',
      renewalDate: '2027-02-01',
      premium: 1260.0,
      documentIds: ['doc_serrano_ciber_cp'],
    }),
    policy({
      id: 'pol_rosa_hogar',
      policyNumber: 'HOG-2026-0808',
      holderPartyId: 'party_rosa',
      insurer: 'Generali',
      product: 'HOGAR',
      productLabel: 'Hogar — Multirriesgo',
      inceptionDate: '2026-04-01',
      renewalDate: '2027-04-01',
      premium: 485.0,
      insuredObjectIds: ['obj_rosa_vivienda'],
      documentIds: ['doc_rosa_hogar_cp'],
      // Anchor D: the ERP and the schedule disagree. Neither wins silently.
      premiumConflict: {
        otherSourceId: 'doc_rosa_hogar_cp',
        otherValue: '512,40 €',
        detail:
          'El ERP registra 485,00 € y las condiciones particulares indican 512,40 €. Diferencia sin resolver.',
      },
    }),
    policy({
      id: 'pol_miguel_auto',
      policyNumber: 'AUT-2025-0640',
      holderPartyId: 'party_miguel',
      insurer: 'AXA',
      product: 'AUTO',
      productLabel: 'Auto — Todo Riesgo con franquicia',
      inceptionDate: '2025-06-01',
      renewalDate: '2027-06-01',
      premium: 812.9,
      previousPremium: 780.0,
      insuredObjectIds: ['obj_miguel_bmw'],
      documentIds: ['doc_miguel_auto_cp_v1', 'doc_miguel_auto_supl'],
    }),
    policy({
      id: 'pol_pilar_salud',
      policyNumber: 'SAL-2026-0122',
      holderPartyId: 'party_pilar',
      insurer: 'Adeslas',
      product: 'SALUD',
      productLabel: 'Salud — Reembolso',
      inceptionDate: '2026-01-01',
      renewalDate: '2027-01-01',
      premium: 1620.0,
    }),
    policy({
      id: 'pol_translog_flota',
      policyNumber: 'FLO-2026-0100',
      holderPartyId: 'org_translog',
      insurer: 'Zurich',
      product: 'FLOTA',
      productLabel: 'Flota — vehículos pesados',
      inceptionDate: '2026-03-15',
      renewalDate: '2027-03-15',
      premium: 18420.0,
      previousPremium: 17100.0,
      insuredObjectIds: ['obj_translog_camion_1'],
    }),
    policy({
      id: 'pol_translog_mercancias',
      policyNumber: 'MER-2026-0044',
      holderPartyId: 'org_translog',
      insurer: 'Mapfre Global Risks',
      product: 'MERCANCIAS',
      productLabel: 'Mercancías en tránsito',
      inceptionDate: '2026-03-15',
      renewalDate: '2027-03-15',
      premium: 6300.0,
      insuredObjectIds: ['obj_translog_mercancias'],
    }),
    policy({
      id: 'pol_sophie_viaje',
      policyNumber: 'VIA-2026-0801',
      holderPartyId: 'party_sophie',
      insurer: 'Chubb',
      product: 'VIAJE',
      productLabel: 'Viaje y estudios — internacional',
      inceptionDate: '2026-09-01',
      renewalDate: '2027-06-30',
      premium: 265.0,
      documentIds: ['doc_sophie_viaje_cp'],
    }),
    policy({
      id: 'pol_sophie_salud',
      policyNumber: 'SAL-2026-0899',
      holderPartyId: 'party_sophie',
      insurer: 'Sanitas',
      product: 'SALUD',
      productLabel: 'Salud — Estudiantes internacionales',
      inceptionDate: '2026-09-01',
      renewalDate: '2027-09-01',
      premium: 720.0,
    }),
  ];

  // ── Coverage terms ─────────────────────────────────────────────────────────
  const coverageTerms = [
    coverageTerm({
      id: 'cvt_ana_auto_franquicia',
      policyId: 'pol_ana_auto',
      kind: 'DEDUCTIBLE',
      key: 'franquicia_danos_propios',
      label: 'Franquicia de daños propios',
      value: '300 €',
      documentId: 'doc_ana_auto_cp',
      passageId: 'doc_ana_auto_cp_p2',
      effectiveFrom: '2026-03-01',
      effectiveTo: '2027-03-01',
    }),
    coverageTerm({
      id: 'cvt_ana_auto_robo_objetos',
      policyId: 'pol_ana_auto',
      kind: 'EXCLUSION',
      key: 'robo_objetos_personales',
      label: 'Objetos personales en el interior del vehículo',
      value: 'No cubiertos salvo garantía de equipaje contratada',
      documentId: 'doc_ana_auto_cg',
      passageId: 'doc_ana_auto_cg_p1',
      effectiveFrom: '2026-03-01',
    }),
    coverageTerm({
      id: 'cvt_ana_hogar_agua',
      policyId: 'pol_ana_hogar',
      kind: 'COVERAGE',
      key: 'danos_por_agua',
      label: 'Daños por agua',
      value: 'Cubiertos, con franquicia de 150 €',
      documentId: 'doc_ana_hogar_cp',
      passageId: 'doc_ana_hogar_cp_p3',
      effectiveFrom: '2026-01-15',
      effectiveTo: '2027-01-15',
    }),
    coverageTerm({
      id: 'cvt_ana_hogar_objetos_valor',
      policyId: 'pol_ana_hogar',
      kind: 'SUBLIMIT',
      key: 'objetos_especial_valor',
      label: 'Sublímite de objetos de especial valor',
      value: '20% del contenido, máximo 3.000 € por objeto salvo tasación',
      documentId: 'doc_ana_hogar_cp',
      passageId: 'doc_ana_hogar_cp_p2',
      effectiveFrom: '2026-01-15',
      effectiveTo: '2027-01-15',
    }),
    // Anchor E: the superseded term stays in the dataset with a closed interval,
    // so retrieval has to choose the current one on the strength of its dates.
    coverageTerm({
      id: 'cvt_miguel_franquicia_v1',
      policyId: 'pol_miguel_auto',
      kind: 'DEDUCTIBLE',
      key: 'franquicia_danos_propios',
      label: 'Franquicia de daños propios (anterior)',
      value: '300 €',
      documentId: 'doc_miguel_auto_cp_v1',
      passageId: 'doc_miguel_auto_cp_v1_p1',
      effectiveFrom: '2025-06-01',
      effectiveTo: '2026-05-20',
    }),
    coverageTerm({
      id: 'cvt_miguel_franquicia_v2',
      policyId: 'pol_miguel_auto',
      kind: 'DEDUCTIBLE',
      key: 'franquicia_danos_propios',
      label: 'Franquicia de daños propios',
      value: '150 €',
      documentId: 'doc_miguel_auto_supl',
      passageId: 'doc_miguel_auto_supl_p1',
      effectiveFrom: '2026-05-21',
      effectiveTo: '2027-06-01',
    }),
    coverageTerm({
      id: 'cvt_serrano_rc_limite',
      policyId: 'pol_serrano_rc',
      kind: 'LIMIT',
      key: 'limite_indemnizacion',
      label: 'Límite de indemnización',
      value: '600.000 € por siniestro y año',
      documentId: 'doc_serrano_rc_cp',
      passageId: 'doc_serrano_rc_cp_p1',
      effectiveFrom: '2026-02-01',
      effectiveTo: '2027-02-01',
    }),
    coverageTerm({
      id: 'cvt_serrano_ciber_franquicia',
      policyId: 'pol_serrano_ciber',
      kind: 'DEDUCTIBLE',
      key: 'franquicia_ciber',
      label: 'Franquicia de ciberriesgo',
      value: '2.500 € por siniestro',
      documentId: 'doc_serrano_ciber_cp',
      passageId: 'doc_serrano_ciber_cp_p1',
      effectiveFrom: '2026-02-01',
      effectiveTo: '2027-02-01',
    }),
    coverageTerm({
      id: 'cvt_sophie_deportes_invierno',
      policyId: 'pol_sophie_viaje',
      kind: 'EXCLUSION',
      key: 'deportes_invierno',
      label: 'Deportes de invierno',
      value: 'Cubiertos en pista señalizada; excluido fuera de pista y competición',
      documentId: 'doc_sophie_viaje_cp',
      passageId: 'doc_sophie_viaje_cp_p2',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-06-30',
    }),
    coverageTerm({
      id: 'cvt_sophie_medicos',
      policyId: 'pol_sophie_viaje',
      kind: 'LIMIT',
      key: 'gastos_medicos',
      label: 'Gastos médicos en el extranjero',
      value: '30.000 €',
      documentId: 'doc_sophie_viaje_cp',
      passageId: 'doc_sophie_viaje_cp_p1',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-06-30',
    }),
    coverageTerm({
      id: 'cvt_rosa_franquicia',
      policyId: 'pol_rosa_hogar',
      kind: 'DEDUCTIBLE',
      key: 'franquicia_general',
      label: 'Franquicia general',
      value: '0 €',
      documentId: 'doc_rosa_hogar_cp',
      passageId: 'doc_rosa_hogar_cp_p2',
      effectiveFrom: '2026-04-01',
      effectiveTo: '2027-04-01',
    }),
  ];

  // ── Claims ─────────────────────────────────────────────────────────────────
  const claims = [
    claim({
      id: 'clm_ana_agua',
      claimNumber: 'SIN-2026-01144',
      policyId: 'pol_ana_hogar',
      holderPartyId: 'party_ana',
      status: 'AWAITING_DOCUMENTS',
      lossDate: '2026-07-11',
      reportedDate: '2026-07-12',
      description: 'Daños por agua en cocina y salón por rotura de latiguillo.',
      chronology: [
        { at: '2026-07-12', party: 'CLIENT', description: 'La clienta comunica los daños por agua.' },
        { at: '2026-07-12', party: 'ROSILLO', description: 'Apertura del expediente y envío a la aseguradora.' },
        { at: '2026-07-14', party: 'INSURER', description: 'Asignación de perito y visita realizada.' },
        { at: '2026-07-18', party: 'INSURER', description: 'Informe pericial recibido. Se solicita factura del latiguillo.' },
        { at: '2026-07-29', party: 'ROSILLO', description: 'Recordatorio de documentación pendiente enviado.' },
      ],
      outstandingItems: [
        { label: 'Factura de reparación del latiguillo', responsible: 'CLIENT' },
        { label: 'Confirmación de valoración final', responsible: 'INSURER' },
      ],
      reserveAmount: 2450,
      documentIds: ['doc_ana_claim_agua'],
    }),
    claim({
      id: 'clm_pilar_salud',
      claimNumber: 'SIN-2026-00877',
      policyId: 'pol_pilar_salud',
      holderPartyId: 'party_pilar',
      status: 'UNDER_REVIEW',
      lossDate: '2026-06-18',
      reportedDate: '2026-06-20',
      description: 'Solicitud de reembolso de asistencia especialista.',
      chronology: [
        { at: '2026-06-20', party: 'CLIENT', description: 'Solicitud de reembolso presentada.' },
        { at: '2026-06-24', party: 'ROSILLO', description: 'Documentación remitida a la aseguradora.' },
      ],
      outstandingItems: [{ label: 'Resolución de la aseguradora', responsible: 'INSURER' }],
      reserveAmount: 380,
      documentIds: ['doc_pilar_salud_parte'],
      specialCategory: true,
    }),
    claim({
      id: 'clm_serrano_rc',
      claimNumber: 'SIN-2026-00450',
      policyId: 'pol_serrano_rc',
      holderPartyId: 'org_serrano',
      status: 'INSURER_ASSESSING',
      lossDate: '2026-05-02',
      reportedDate: '2026-05-05',
      description: 'Reclamación de un cliente por daños en vehículo durante la custodia en el taller.',
      chronology: [
        { at: '2026-05-05', party: 'CLIENT', description: 'La empresa comunica la reclamación recibida.' },
        { at: '2026-05-06', party: 'ROSILLO', description: 'Apertura y traslado a la aseguradora.' },
        { at: '2026-06-11', party: 'INSURER', description: 'Peritación en curso.' },
      ],
      outstandingItems: [{ label: 'Valoración del perito', responsible: 'INSURER' }],
      reserveAmount: 4100,
    }),
    claim({
      id: 'clm_carlos_auto',
      claimNumber: 'SIN-2026-01201',
      policyId: 'pol_carlos_auto',
      holderPartyId: 'party_carlos',
      status: 'SETTLED',
      lossDate: '2026-04-03',
      reportedDate: '2026-04-03',
      description: 'Golpe en aparcamiento sin terceros identificados.',
      chronology: [
        { at: '2026-04-03', party: 'CLIENT', description: 'Comunicación del siniestro.' },
        { at: '2026-04-20', party: 'INSURER', description: 'Reparación autorizada y abonada.' },
      ],
      reserveAmount: 0,
    }),
  ];

  // ── Receipts ───────────────────────────────────────────────────────────────
  const receipts = [
    receipt({
      id: 'rec_ana_auto_1',
      receiptNumber: 'REC-2026-100341',
      policyId: 'pol_ana_auto',
      amount: 371.15,
      dueDate: '2026-03-01',
      status: 'PAID',
      paidAt: '2026-03-02',
      periodFrom: '2026-03-01',
      periodTo: '2026-09-01',
    }),
    receipt({
      id: 'rec_ana_auto_2',
      receiptNumber: 'REC-2026-100342',
      policyId: 'pol_ana_auto',
      amount: 371.15,
      dueDate: '2026-09-01',
      status: 'PENDING',
      periodFrom: '2026-09-01',
      periodTo: '2027-03-01',
    }),
    receipt({
      id: 'rec_ana_hogar_1',
      receiptNumber: 'REC-2026-100122',
      policyId: 'pol_ana_hogar',
      amount: 389.0,
      dueDate: '2026-01-15',
      status: 'PAID',
      paidAt: '2026-01-15',
      periodFrom: '2026-01-15',
      periodTo: '2027-01-15',
    }),
    receipt({
      id: 'rec_rosa_hogar_1',
      receiptNumber: 'REC-2026-100908',
      policyId: 'pol_rosa_hogar',
      amount: 485.0,
      dueDate: '2026-04-01',
      status: 'RETURNED',
      periodFrom: '2026-04-01',
      periodTo: '2027-04-01',
    }),
    receipt({
      id: 'rec_serrano_rc_1',
      receiptNumber: 'REC-2026-200033',
      policyId: 'pol_serrano_rc',
      amount: 1240.0,
      dueDate: '2026-02-01',
      status: 'PAID',
      paidAt: '2026-02-03',
      periodFrom: '2026-02-01',
      periodTo: '2026-08-01',
    }),
    receipt({
      id: 'rec_serrano_rc_2',
      receiptNumber: 'REC-2026-200034',
      policyId: 'pol_serrano_rc',
      amount: 1240.0,
      dueDate: '2026-08-01',
      status: 'PENDING',
      periodFrom: '2026-08-01',
      periodTo: '2027-02-01',
    }),
    receipt({
      id: 'rec_miguel_auto_1',
      receiptNumber: 'REC-2026-100640',
      policyId: 'pol_miguel_auto',
      amount: 812.9,
      dueDate: '2026-06-01',
      status: 'PAID',
      paidAt: '2026-06-01',
      periodFrom: '2026-06-01',
      periodTo: '2027-06-01',
    }),
  ];

  return {
    parties,
    relationships,
    accounts,
    policies,
    insuredObjects,
    coverageTerms,
    claims,
    receipts,
    documents,
    procedures: [],
  };
}
